---
Name: dataobjectlinkmodule
After:
  - '#cmsmodals'
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'flxlabs/silverstripe-dataobject-links:client/dist/js/sslink-dataobject-transforms.js'

SilverStripe\Admin\ModalController:
  link_modal_form_factories:
    editorDataObjectLink: FLXLabs\DataObjectLink\DataObjectLinkFormFactory
