---
Name: dataobjectlinkmodule
After:
  - '#cmsmodals'
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'vendor/flxlabs/silverstripe-dataobject-links/client/dist/js/sslink-dataobject-transforms.js'
  extensions:
    - FLXLabs\DataObjectLink\DataObjectLinkExtension

SilverStripe\Admin\ModalController:
  link_modal_form_factories:
    EditorDataObjectLink: FLXLabs\DataObjectLink\DataObjectLinkFormFactory
  extensions:
    - FLXLabs\DataObjectLink\DataObjectLinkModalExtension
